### ISSUE TITLE
Вылет при попытке рисовать на определённых отрицательных координатах + на всех отрицательных блоках не рисуется первый слева тайл

### ISSUE THREAD

**Issue by MrShurukan** [codename-scp-community/web-editor#16]
Ошибка в расчёте координат для отрицательных блоков приводит к тому, что на блоках с отрицательным иксом невозможно нарисовать первый слева тайл, а на блоках с отрицательным игреком происходит вылет при попытке рисовать на первом сверху тайле

**Comment by shtrih** [comment]
Если посчитать позицию тайла в блоке, позиция которого на сетке, например, `-60`, то  получим `30` (`30 - (60 % 30)`), а ожидается `0`, ибо возможные позиции в блоке `0..29`.
